[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
clize = "^5.0.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
ruff = "^0.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
