name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  uses: olafurpg/setup-scala@v14
         with:
          java-version: 17
      - name: Build and Test
        run: sbt -v test IntegrationTest/test
        working-directory: 001-wc
