name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  uses: actions/setup-java@v4
         with:
           distribution: corretto
           java-version: 21
      - name: Build and Test
        run: sbt -v test IntegrationTest/test
        working-directory: 001-wc
