name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: olafurpg/setup-scala@v14
        with:
          distribution: corretto
          java-version: 21
      - name: Build and Test
        run: sbt -v test IntegrationTest/test
        working-directory: 001-wc
